---
before_install:
    - 'docker build -t matusdubrava/docker-react -f Dockerfile.dev .'
script:
    - 'docker container run matusdubrava/docker-react npm run test -- --coverage'
services:
    - docker
sudo: required
deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'docker'
    env: 'Docker-env'
    bucket_name: 'elasticbeanstalk-us-east-1-859119227216'
    bucket_path: 'docker'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: '$AWS_SECRET_KEY'
