---
before_install:
    - 'docker build -t matusdubrava/docker-react -f Dockerfile.dev .'
script:
    - 'docker container run matusdubrava/docker-react npm run test -- --coverage'
services:
    - docker
sudo: required
# deploy:
#     provider: elasticbeanstalk
#     region: 'us-east-1'
#     app: 'name-of-the-application'
#     env: 'name-of-the-environment'
#     bucket_name: 'name-of-s3-bucket-generated-by-elasticbeanstalk'
#     bucket_path: 'path-to-application-folder-in-the-s3-bucket'
#     on:
#         branch: master
