---
before_install:
    - 'docker build -t matusdubrava/docker-react -f Dockerfile.dev .'
script:
    - 'docker container run matusdubrava/docker-react npm run test -- --coverage'
services:
    - docker
sudo: required
